version: '3.8'

services:
  cine-agent:
    build: .
    container_name: cine_agent
    ports:
      - "8501:8501" # Porta padrão do Streamlit
    volumes:
      - .:/app # Mapeia a pasta atual para o container
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Puxa a GEMINI API KEY do .env
    command: streamlit run src/app.py --server.address=0.0.0.0