services:
  cine-agent:
    build: .
    container_name: cine_agent
    network_mode: host
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://localhost:11434
    command: streamlit run src/app.py --server.address=0.0.0.0